<?php

namespace ZRR\CandidatureBundle\Repository;

/**
 * DirigerLaboRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DirigerLaboRepository extends \Doctrine\ORM\EntityRepository
{
}
