<?php

namespace ZRR\CandidatureBundle\Repository;

/**
 * DirigerZrrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DirigerZrrRepository extends \Doctrine\ORM\EntityRepository
{
}
