<?php

namespace ZRR\CandidatureBundle\Repository;

/**
 * DomainescientifiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomainescientifiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
