<?php

namespace ZRR\CandidatureBundle\Repository;

/**
 * InfoComplRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoComplRepository extends \Doctrine\ORM\EntityRepository
{
}
