<?php

namespace ZRR\CandidatureBundle\Repository;

/**
 * LaboratoireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LaboratoireRepository extends \Doctrine\ORM\EntityRepository
{
    /*public function getDirecteurCourant($id){
        $qb = $this->createQueryBuilder('l')->where('l.id=:id')
            ->setParameter('id', $id)
        ->leftJoin('l.dirigerLabos', 'dl')->addSelect('dl')
            ->andWhere('dl.dateDebut <= :now')
            //->andWhere('dl.dateFin > :now')
            ->setParameter('now', new \DateTime('now'))
            ->leftJoin('dl.responsableLabo', 'resp')->addSelect('resp');

        return $qb->getQuery()->getOneOrNullResult();

    }*/
}
