security:
    encoders:
        ZRR\UserBundle\Entity\User: sha512
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        # Un admin hérite des droits d'auteur et de modérateur
        ROLE_ADMIN:       [ROLE_CDD, ROLE_RESP_SCI, ROLE_RESP_LABO]
        # On garde ce rôle superadmin, il nous resservira par la suite
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main_login:
            pattern: ^/(login$|register/confirmed|register/confirm)
            anonymous: true

        main:
            pattern:      ^/
            anonymous:    true
            provider:     main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                #csrf_token_generator: security.csrf.token_manager
                success_handler: redirect.after.login
            logout:
                path:       fos_user_security_logout
                target:     fos_user_security_login
            remember_me:
                secret:     %secret% # %secret% est un paramètre de parameter

    access_control:
        #- { path: ^/register, roles: ROLE_RESP_SCI }
        #- { path: ^/candidat, roles: ROLE_CDD}
        #- { path: ^/activite, roles: ROLE_RESP}
        - { path: ^/register/$, roles: [ROLE_ADMIN, ROLE_RESP_SCI] }