<?php

namespace ZRR\CandidatureBundle\Repository;

/**
 * ActiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActiviteRepository extends \Doctrine\ORM\EntityRepository
{
    //requete qui renvoie les activités créées par le responsable scientifique
    public function findActivite($idResp){
        $queryBuilder = $this
            ->createQueryBuilder('a')
            ->leftJoin('a.responsableSci', 'resp')
            ->addSelect('resp')
            ->where('resp.id=:idr')
            ->setParameter('idr', $idResp);
        $query = $queryBuilder->getQuery();
        $results = $query->getResult();
        return $results;

    }

    //requete qui renvoie les activités et candidats liés du responsable scientifique
    public function findCddandAct($idResp){
        $queryBuilder = $this->createQueryBuilder('a')
            ->leftJoin('a.responsableSci', 'resp')
            ->addSelect('resp')
            ->where('resp.id=:idr')
            ->setParameter('idr', $idResp)
            ->leftJoin('a.dossier', 'doss')
            ->addSelect('doss')
            ;//     ->leftJoin('doss.candidat', 'cdd')->addSelect('cdd');

        $query = $queryBuilder->getQuery();
        $results = $query->getResult();
        return $results;
    }
}
