<?php

namespace ZRR\CandidatureBundle\Repository;

/**
 * CandidatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CandidatRepository extends \Doctrine\ORM\EntityRepository
{
    //renvoie le candidat lié à l'activité passée en paramètre
    public function findCddofAct($idAct){
        $queryBuilder = $this->createQueryBuilder('c')
            ->leftJoin('c.dossiers', 'doss')->addSelect('doss')
            ->leftJoin('doss.activite', 'act')->addSelect('act')
            ->where('act.id=:ida')->setParameter('ida', $idAct);
        $query = $queryBuilder->getQuery();
        $results = $query->getOneOrNullResult();
        return $results;
    }


}
