<?php

namespace ZRR\CandidatureBundle\Repository;

/**
 * DisciplinescientifiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisciplinescientifiqueRepository extends \Doctrine\ORM\EntityRepository
{
    public function getDisciplines($idDomaine){
        $queryBuilder = $this->createQueryBuilder('disc')
            ->leftJoin('disc.domaineScientifique', 'dom')->addSelect('dom')
            ->where('dom.id=:iddom')->setParameter('iddom', $idDomaine)
            ->orderBy('disc.nom', 'ASC');
        $query = $queryBuilder->getQuery();
        $results = $query->getArrayResult();
        return $results;
    }
    /*public function getDisciplines($id) //Using
    {
        $queryBuilder = $this->_em->createQueryBuilder();

        $queryBuilder->select('d')
            ->from('ZRRCandidatureBundle:Disciplinescientifique', 'd')
            ->where('d.Disciplinescientifique = :id')
            ->setParameter('id', $id)
            ->orderBy('d.nom', 'ASC')
            ->groupBy('d.nom');

        return $queryBuilder->getQuery()
            ->getArrayResult();
    }*/
}
