<?php

namespace ZRR\CandidatureBundle\Repository;

/**
 * ResponsableSciRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponsableSciRepository extends \Doctrine\ORM\EntityRepository
{

}
