<?php

namespace ZRR\CandidatureBundle\Repository;

/**
 * ResponsableLaboRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponsableLaboRepository extends \Doctrine\ORM\EntityRepository
{
    public function getDirecteurCourant($id){
        $qb = $this->createQueryBuilder('resp');
            $qb->select('resp')
            ->leftJoin('resp.dirigerLabos', 'dl')->addSelect('dl')
            ->andWhere('dl.dateDebut <= :now')
            ->andWhere($qb->expr()->orX(
                'dl.dateFin>:now',
                $qb->expr()->isNull('dl.dateFin')
                ))
                ->setParameter('now', new \DateTime())
            ->leftJoin('dl.laboratoire', 'labo')->addSelect('labo')
            ->andWhere('labo.id=:id')
            ->setParameter('id', $id)
            ;

        return $qb->getQuery()->getOneOrNullResult();

    }
}
