<?php

namespace ZRR\CandidatureBundle\Repository;

/**
 * SecretaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecretaireRepository extends \Doctrine\ORM\EntityRepository
{
}
