<?php

namespace ZRR\CandidatureBundle\Repository;

/**
 * ZrrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZrrRepository extends \Doctrine\ORM\EntityRepository
{
    //renvoie les zrrs du laboratoire en paramètre
    public function getZrrInLabo($idLabo){
        $qb = $this->createQueryBuilder('z');
        $qb->where('z.laboratoire = :labo')->setParameter('labo', $idLabo);

        return $qb->getQuery()->getResult();

    }
}
